---
# tasks for installing on debian
- name: Install prerequisites
  ansible.builtin.apt:
    pkg: 
      - gpg
      - curl

- name: Add cloudsmith kea repos key
  ansible.builtin.shell: "curl -1sLf 'https://dl.cloudsmith.io/public/isc/kea-{{ kea_file_version }}/gpg.D4FEAEAEFBD81FB9.key' |  gpg --dearmor >> {{ kea_keyring_location }}"
  args:
    creates: "{{ kea_keyring_location }}"

- name: Add cloudsmith kea deb repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ kea_keyring_location }}]  https://dl.cloudsmith.io/public/isc/kea-{{ kea_file_version }}/deb/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    state: present
    filename: isc-kea-{{ kea_file_version }}
    
- name: Add cloudsmith kea deb-src repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb-src [signed-by={{ kea_keyring_location }}]  https://dl.cloudsmith.io/public/isc/kea-{{ kea_file_version }}/deb/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    state: present
    filename: isc-kea-{{ kea_file_version }}
    
- name: Install kea packages
  ansible.builtin.apt:
    pkg: 
      - isc-kea
