---
# tasks for dhcp4

- name: Disable DHCP 4
  when: not kea_dhcp4
  ansible.builtin.service:
    name: isc-kea-dhcp4-server
    enabled: no
    state: stopped


- name: Configure DHCP 4 
  when: kea_dhcp4
  ansible.builtin.template:
    src: kea-dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
    mode: '0640'
    owner: "{{ kea_user }}"
    group: "{{ kea_group }}"
    validate: "validate.sh kea-dhcp4 -t %s"
  notify: restart dhcp4
