---
# tasks file for kea
- name: Helpers
  include_tasks: helpers.yml

- block:
  - name: Include installation
    include_tasks: debian_install.yml
  when: kea_install

- name: Configure PostgreSQL
  include_tasks: config_pg.yml
  when: kea_pg

- name: Include DHCP 4
  include_tasks: dhcp4.yml
    
- name: Include DHCP 6
  include_tasks: dhcp6.yml

- name: Include ddns
  include_tasks: ddns.yml
  when: (kea_dhcp4_ddns | bool) or (kea_dhcp6_ddns | bool)

- name: Configure Ctrl Agent
  ansible.builtin.template:
    src: kea-ctrl-agent.conf.j2
    dest: /etc/kea/kea-ctrl-agent.conf
    mode: '0640'
    owner: "{{ kea_user }}"
    group: "{{ kea_group }}"
    validate: "kea-ctrl-agent -t %s"
  notify: restart ctrl agent
