---
# handlers file for kea
- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes

# - name: Validate dhcp4 config
#   ansible.builtin.command:
#     cmd: kea-dhcp4 -t /etc/kea/kea-dhcp4.conf
#   listen: restart dhcp4

- name: Restart dhcp4 service
  ansible.builtin.systemd:
    name: isc-kea-dhcp4-server
    state: restarted
    enabled: yes
  listen: restart dhcp4

# - name: Validate dhcp6 config
#   ansible.builtin.command:
#     cmd: kea-dhcp6 -t /etc/kea/kea-dhcp6.conf
#   listen: restart dhcp6

- name: Restart dhcp6 service
  ansible.builtin.systemd:
    name: isc-kea-dhcp6-server
    state: restarted
    enabled: yes
  listen: restart dhcp6

- name: restart ctrl agent
  ansible.builtin.systemd:
    name: isc-kea-ctrl-agent
    state: restarted
    enabled: yes

- name: Validate dhcp-ddns config
  ansible.builtin.command:
    cmd: kea-dhcp-ddns -t /etc/kea/kea-dhcp-ddns.conf
  listen: restart dhcp-ddns

- name: Restart dhcp-ddns service
  ansible.builtin.systemd:
    name: isc-kea-dhcp-ddns-server
    state: restarted
    enabled: yes
  listen: restart dhcp-ddns
