---
# handlers file for kea
- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: reload dhcp4
  ansible.builtin.systemd:
    name: isc-kea-dhcp4-server
    state: reloaded
    enabled: yes

- name: reload dhcp6
  ansible.builtin.systemd:
    name: isc-kea-dhcp6-server
    state: reloaded
    enabled: yes    

- name: reload ctrl agent
  ansible.builtin.systemd:
    name: isc-kea-ctrl-agent
    state: reloaded
    enabled: yes