---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: debian/bullseye
    # pre_build_image: true
    dockerfile: ../common/Dockerfile.j2
provisioner:
  name: ansible
verifier:
  name: ansible
