---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ molecule_no_log }}"
  tasks:
    # TODO: Developer must implement and populate 'server' variable
    - name: create instances
      include_tasks: tasks/create_instance.yml
      loop: "{{ molecule_yml.platforms }}"

    - name: show created
      debug:
        var: instance_created


    - name: Populate instance config dict
      ansible.builtin.set_fact:
        instance_config_dict: {
          'instance': "{{ item.name }}",
          'connection': "community.general.incus", 
        }
      with_items: "{{ instance_created.instances }}"
      register: instance_config_dict
      when: instance_created.changed

    - name: show instance_config_dict
      debug:
        var: instance_config_dict

    # - name: Create instance config
    #   when: server.changed | default(false) | bool  # noqa no-handler
    #   block:
    #     - name: Populate instance config dict  # noqa jinja
    #       ansible.builtin.set_fact:
    #         instance_conf_dict: {}
    #         # instance': "{{ }}",
    #         # address': "{{ }}",
    #         # user': "{{ }}",
    #         # port': "{{ }}",
    #         # 'identity_file': "{{ }}", }
    #       with_items: "{{ server.results }}"
    #       register: instance_config_dict

    - name: Convert instance config dict to a list
      ansible.builtin.set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_config_dict') | list }}"

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
